---
title: "Likelihood profiles"
author: "William T. Stockhausen"
institute: "AFSC/NMFS/NOAA"
date: '`r format(Sys.time(), "%b %e, %Y")`'
fontsize: 11pt 
number-sections: false
number-depth: 3
reference-location: document
reference-section-title: References
bibliography: /Users/williamstockhausen/Work/Projects/Bibliography/AllRefs.bib
csl: '`r system.file("files/CJFAS.csl",package="wtsQMD")`'
link-citations: true
crossref:
  chapters: false      # prepend label reference numbers by chater number?
  fig-title: Figure    # for caption: default is "Figure")
  tbl-title: Table     # for caption: default is "Table")
  title-delim: "."     # for caption: default is ":")
  fig-prefix: Figure   # for in-text (use [-@fig-ref] to drop prefix in text)
  tbl-prefix: Table    # for in-text (use [-@tbl-ref] to drop prefix in text)
  fig-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  tbl-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  subref-labels: alpha a # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  ref-hyperlink: true    # references are hyperlinked if true
format: 
  html: 
    df-print: paged
    toc: true
    toc-location: right
    fig-width: 6.5
    fig-asp: 0.6
    fig-dpi: 100
    embed-resources: true
  pdf:
    documentclass: scrartcl
    toc: false
    fig_crop: false
    keep-tex: false
    fig-width: 6.5
    fig-asp: 0.6
    fig-dpi: 100
    geometry:
      - left=1.0in
      - right=1.0in
      - top=1.0in
      - bottom=1.0in
      - textwidth=6.5in
      - showframe=false
    include-in-header: 
      - text: |
          \usepackage{placeins}
          \extrafloats{500}
          \maxdeadcycles=10000
          \usepackage{fontspec}
          \usepackage{multicol}
          \usepackage{hhline}
          \newlength\Oldarrayrulewidth
          \newlength\Oldtabcolsep
      - file: '`r system.file("files/ltx_ExtraLatexIncludes.tex",package="wtsQMD")`'
echo: false
warning: false
results: 'hide'
keep-md: false
keep-yaml: false
editor: source
editor_options: 
  chunk_output_type: console
concordance: true
params:
  setup: !expr 'system.file("files/qmd_setup.R",package="wtsQMD")'
  testing: false
  reorderTables: false   #--issue with finding "range" of table values  (don't use)
  reorderFigures: false  #--issue with finding "range" of figure values (don't use)
  param: "pQ[2]"
  param_str: "NMFS male catchability (1982+)"
  calcParams: false
---
<!-- IMPORTANT: if used as a child doc, all chunk labels must be unique within the overall document -->

<!-- 
  NOTEs: 
     * child_path$peek() gives path to current script.
     * before starting a child document, do 
         "child_path$push(file.path(child_path$peek(),rel_path))" first, 
         where rel_path is the relative path to the child
     * after a child document has finished, do "child_path$pop()" to return to current path value
-->

<!-- if not child doc, set up required objects -->
```{r}
#| label: LPs-Params_setup
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: "asis"
  testing = params$testing;
  if (testing) cat(params$setup,"\n\n")
  source(params$setup);
  if (testing) cat("root = ",root,"\n\n")
  reorderTables  = params$reorderTables;
  reorderFigures = params$reorderFigures;
  param          = params$param;
  param_str      = params$param_str;

```

```{r}
#| label: setup_LPs-Params
#| results: 'asis'
  require(ggplot2);
  require(kableExtra);
  require(tables);
  Sum = wtsUtilities::Sum;
  old_thm = ggplot2::theme_set(cowplot::theme_cowplot(font_size = 10) +
                               cowplot::background_grid() +
                               cowplot::panel_border());
  thm = wtsPlots::getStdTheme();
  options("readr.show_col_types"=FALSE);
  if (testing) cat("dirThs =",child_path$peek(),"\n\n")

  dirThs = child_path$peek();                #--path to "this" folder
  if (rstudioapi::isAvailable()) dirThs = dirname(rstudioapi::getActiveDocumentContext()$path);
  dirPrj = file.path(child_path$peek(),"..");#--path to project folder from "this" folder
  
  if (!exists("tblno")) tblno = 0;
```

```{r LPs-Params-GetPlottingInfo}
legPosUR = ggplot2::theme(legend.position="inside",
                          legend.position.inside=c(0.99,0.99),
                         legend.justification.inside=c(1,1));
legPosUL = theme(legend.position="inside",
                 legend.position.inside=c(0.01,0.99),
                 legend.justification.inside=c(0,1));
noLeg = ggplot2::theme(legend.position="none");
noTitle  = ggplot2::theme(plot.title=element_blank());
noXTitle = ggplot2::theme(axis.title.x=element_blank());
noTTitle = ggplot2::theme(axis.title.y=element_blank());
colour_scale=ggplot2::scale_color_hue();
fill_scale  =ggplot2::scale_fill_hue();
```

```{r LP_CalcResultsParams}
  #--calculate model cases----
  cases = wtsUtilities::getObj(file.path(dirThs,"rda_cases.RData"));
  base = as.character(cases[1]);
  if (params$calcParams){
    lst<-list();
    for (case_ in cases){
      fn = paste0(file.path(dirThs,paste0("./LP_Results/Results_",case_,".RData")));
      if (file.exists(fn)){
        load(fn);
        if (!is.null(best$rep)){
          casep = as.character(case_);
          dfrp<-rTCSAM02::getMDFR.ParameterValues(best) |> 
                  dplyr::mutate(case=casep);
          lst[[casep]]<-dfrp;
          rm(casep,dfrp);
        }
        rm(best);
      }
      rm(fn);
    }#--case
    dfrPs = dplyr::bind_rows(lst); #rm(lst);
    dfrPsBase = dfrPs |> 
                  dplyr::filter(case==base) |> 
                  dplyr::mutate(base=final_arith_value) |> 
                  dplyr::filter(phase>0) |>
                  dplyr::select(category,process,label,type,name,index,base);
    dfrPds = dfrPs |> 
               dplyr::inner_join(dfrPsBase,
                                 by=dplyr::join_by(category,process,label,type,name,index)) |> 
               dplyr::mutate(diff=final_arith_value-base,
                             pct=100*diff/abs(base),
                             case=as.numeric(case)) |> 
               dplyr::select(!c(min_param,max_param,init_param_value,final_param_value,stdv));
    wtsUtilities::saveObj(dfrPds,file.path(dirThs,"rda_dfrParamDiffs.RData"));
  }
```

```{r LPs-Params-GetResultsParams}
  #--plot parameter profiles
  dfrPds = wtsUtilities::getObj(file.path(dirThs,"rda_dfrParamDiffs.RData"));
```

```{r}
  ti = paste0(param," (",param_str,") ");
  rf = paste0("sec-LP-ParDifs-",wtsQMD::sanitizeLabels(param));
```

## Likelihood profile results for profiling on `r paste0(ti, " {#",rf,"}")`

```{r}
#| label: fig_LPs-ParDifs-
#| results: "asis"
#| fig-width: 6.0
#| fig-asp: 1
  uCPs = dfrPds |> dplyr::filter(category!="selectivity") |> dplyr::distinct(category,process);
  for (rw in 1:nrow(uCPs)){
    #--testing: rw = 1;
    tmp1<-dfrPds |>
            dplyr::inner_join(uCPs[rw,,drop=FALSE],by=dplyr::join_by(category,process)) |>
            dplyr::filter(type==" param_init_bounded_number");
    if (nrow(tmp1)>0){
      ctg = uCPs$category[rw];
      prc = uCPs$process[rw];
      subt = paste0(ctg,": ",prc);
      tmp2 = tmp1 |> dplyr::distinct(name,label);
      str = paste0(tmp2$name,": ",tmp2$label,".",collapse=" ");
      p = ggplot(tmp1,mapping=aes(x=case,y=diff,colour=name)) +
            geom_hline(yintercept=0,linetype=3) +
            geom_vline(xintercept=as.numeric(cases[1]),linetype=3) +
            geom_line() +
            labs(x=param,y="parameter change (value-base)",colour="parameter",
                 subtitle=subt) +
            wtsPlots::getStdTheme();
      xtra=paste0("AD-",ctg,"-",prc);
      lbl = wtsQMD::getLabel(xtra);
      cap = paste0('Absolute parameter differences in model category "',ctg,'" and process "',prc,'". ',str);
      pth = wtsQMD::getFigFN(xtra);
      lstFigs = c(lstFigs,wtsQMD::printGGplot(p,pth=pth,lbl=lbl,cap=cap,ori="P"));
      p = ggplot(tmp1,mapping=aes(x=case,y=pct,colour=name)) +
            geom_hline(yintercept=0,linetype=3) +
            geom_vline(xintercept=as.numeric(cases[1]),linetype=3) +
            geom_line() +
            labs(x=param,y="parameter change as percentage: 100*(value-base)/base",colour="parameter",
                 subtitle=subt) +
            wtsPlots::getStdTheme();
      xtra=paste0("PD-",ctg,"-",prc)
      lbl = wtsQMD::getLabel(xtra);
      cap = paste0('Proportional parameter differences in model category "',ctg,'" and process "',prc,'".')
      pth = wtsQMD::getFigFN(xtra);
      lstFigs = c(lstFigs,wtsQMD::printGGplot(p,pth=pth,lbl=lbl,cap=cap,ori="P"));
    }
  }
  rm(lbl,cap,pth)
```

```{r}
#| label: fig_LPs-ParDifs-Sels
#| results: "asis"
#| fig-width: 6.0
#| fig-asp: 1
  nPmx = 8;#--largest number of parameters in a plot
  uPNs = dfrPds |> dplyr::filter(category=="selectivity",!stringr::str_starts(name,"pDevs")) |> 
                   dplyr::distinct(process,name=stringr::str_sub(name,1,3));
  for (rw in 1:nrow(uPNs)){
    #--testing: rw = 1;
    tmp1<-dfrPds |> dplyr::mutate(starts_=stringr::str_sub(name,1,3)) |>
            dplyr::inner_join(uPNs[rw,,drop=FALSE],by=dplyr::join_by(process,x$starts_==y$name)) |>
            dplyr::filter(type==" param_init_bounded_number");
    if (nrow(tmp1)>0){
      uPNps = tmp1 |> dplyr::distinct(name);
      nplts = ceiling(nrow(uPNps)/nPmx);
      for (irw in 1:nplts){
        rwstrt = nPmx*(irw-1) + 1;
        rwend  = min(rwstrt+nPmx-1,nrow(uPNps));
        tmp2 = dfrPds |> dplyr::filter(name %in% uPNps$name[rwstrt:rwend]);
        if (nrow(tmp2)>0){
          subt = paste0("selectivity: ",uPNs$name[rw]," parameters");
          p = ggplot(tmp2,mapping=aes(x=case,y=diff,colour=name)) +
                geom_hline(yintercept=0,linetype=3) +
                geom_vline(xintercept=as.numeric(cases[1]),linetype=3) +
                geom_line() +
                labs(x=param,y="parameter difference",colour="parameter",
                     subtitle=subt) +
                wtsPlots::getStdTheme();
          tmp3 = tmp2 |> dplyr::distinct(name,label);
          str = paste0(tmp3$name,": ",tmp3$label,".",collapse=" ")
          xtra=paste0("AD-",stringr::str_sub(uPNps$name[1],1,3),"-",irw);
          lbl = wtsQMD::getLabel(xtra);
          cap = paste0('Absolute selectivity parameter differences. ',str);
          pth = wtsQMD::getFigFN(xtra);
          lstFigs = c(lstFigs,wtsQMD::printGGplot(p,pth=pth,lbl=lbl,cap=cap,ori="P"));
          p = ggplot(tmp2,mapping=aes(x=case,y=pct,colour=name)) +
                geom_hline(yintercept=0,linetype=3) +
                geom_vline(xintercept=as.numeric(cases[1]),linetype=3) +
                geom_line() +
                labs(x=param,y="parameter percent difference",colour="parameter",
                     subtitle=subt) +
                wtsPlots::getStdTheme();
          xtra=paste0("PD-",stringr::str_sub(uPNps$name[1],1,3),"-",irw);
          lbl = wtsQMD::getLabel(xtra);
          cap = paste0('Proportional selectivity parameter differences. ',str);
          pth = wtsQMD::getFigFN(xtra);
          lstFigs = c(lstFigs,wtsQMD::printGGplot(p,pth=pth,lbl=lbl,cap=cap,ori="P"));
        }#--if
      }#--irw
    }#--if (nrow(itmp1)>0)
  }#--rw
  rm(lbl,cap,pth)
```


<!-- references -->
```{r,eval=!knitr::opts_knit$get("child")&!isPDF,results='asis'}
  cat("# References {-}\n");
  cat("::: {#refs}\n");
  cat(":::\n\n");
```

<!-- tables, if not child doc and lstTbls is not empty -->
```{r}
#| label: tables_LPs-Params
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printTablesSectionFromList.R",package="wtsQMD"));
```

<!-- figures, if not child doc and lstFigs is not empty -->
```{r}
#| label: figures_LPs-Params
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printFiguresSectionFromList.R",package="wtsQMD"));
```
