---
title: "Likelihood profiles: Management Quantities"
author: "William T. Stockhausen"
institute: "AFSC/NMFS/NOAA"
date: '`r format(Sys.time(), "%b %e, %Y")`'
fontsize: 11pt 
number-sections: false
number-depth: 3
reference-location: document
reference-section-title: References
bibliography: /Users/williamstockhausen/Work/Projects/Bibliography/AllRefs.bib
csl: '`r system.file("files/CJFAS.csl",package="wtsQMD")`'
link-citations: true
crossref:
  chapters: false      # prepend label reference numbers by chater number?
  fig-title: Figure    # for caption: default is "Figure")
  tbl-title: Table     # for caption: default is "Table")
  title-delim: "."     # for caption: default is ":")
  fig-prefix: Figure   # for in-text (use [-@fig-ref] to drop prefix in text)
  tbl-prefix: Table    # for in-text (use [-@tbl-ref] to drop prefix in text)
  fig-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  tbl-labels: arabic    # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  subref-labels: alpha a # options are arabic, roman, roman i, alpha x, alpha X; latter two starting from x/X
  ref-hyperlink: true    # references are hyperlinked if true
format: 
  html: 
    df-print: paged
    toc: true
    toc-location: right
    fig-width: 6.5
    fig-asp: 0.6
    fig-dpi: 100
    embed-resources: true
  pdf:
    documentclass: scrartcl
    toc: false
    fig_crop: false
    keep-tex: false
    fig-width: 6.5
    fig-asp: 0.6
    fig-dpi: 100
    geometry:
      - left=1.0in
      - right=1.0in
      - top=1.0in
      - bottom=1.0in
      - textwidth=6.5in
      - showframe=false
    include-in-header: 
      - text: |
          \usepackage{placeins}
          \extrafloats{500}
          \maxdeadcycles=10000
          \usepackage{fontspec}
          \usepackage{multicol}
          \usepackage{hhline}
          \newlength\Oldarrayrulewidth
          \newlength\Oldtabcolsep
      - file: '`r system.file("files/ltx_ExtraLatexIncludes.tex",package="wtsQMD")`'
echo: false
warning: false
results: 'hide'
keep-md: false
keep-yaml: false
editor: source
editor_options: 
  chunk_output_type: console
concordance: true
params:
  setup: !expr 'system.file("files/qmd_setup.R",package="wtsQMD")'
  testing: false
  reorderTables: false   #--issue with finding "range" of table values  (don't use)
  reorderFigures: false  #--issue with finding "range" of figure values (don't use)
  param: "pQ[2]"
  param_str: "NMFS male catchability (1982+)"
  calcParams: true
---
<!-- IMPORTANT: if used as a child doc, all chunk labels must be unique within the overall document -->

<!-- 
  NOTEs: 
     * child_path$peek() gives path to current script.
     * before starting a child document, do 
         "child_path$push(file.path(child_path$peek(),rel_path))" first, 
         where rel_path is the relative path to the child
     * after a child document has finished, do "child_path$pop()" to return to current path value
-->

<!-- if not child doc, set up required objects -->
```{r}
#| label: LPs-MQs_setup
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: "asis"
  testing = params$testing;
  if (testing) cat(params$setup,"\n\n")
  source(params$setup);
  if (testing) cat("root = ",root,"\n\n")
  reorderTables  = params$reorderTables;
  reorderFigures = params$reorderFigures;
  param          = params$param;
  param_str      = params$param_str;

```

```{r}
#| label: setup_LPs-MQs
#| results: 'asis'
  require(ggplot2);
  require(kableExtra);
  require(tables);
  Sum = wtsUtilities::Sum;
  old_thm = ggplot2::theme_set(cowplot::theme_cowplot(font_size = 10) +
                               cowplot::background_grid() +
                               cowplot::panel_border());
  thm = wtsPlots::getStdTheme();
  options("readr.show_col_types"=FALSE);
  if (testing) cat("dirThs =",child_path$peek(),"\n\n")

  dirThs = child_path$peek();                #--path to "this" folder
  if (rstudioapi::isAvailable()) dirThs = dirname(rstudioapi::getActiveDocumentContext()$path);
  dirPrj = file.path(child_path$peek(),"..");#--path to project folder from "this" folder
  
  if (!exists("tblno")) tblno = 0;
```

```{r LPs-MQs-GetPlottingInfo}
legPosUR = ggplot2::theme(legend.position="inside",
                          legend.position.inside=c(0.99,0.99),
                         legend.justification.inside=c(1,1));
legPosUL = theme(legend.position="inside",
                 legend.position.inside=c(0.01,0.99),
                 legend.justification.inside=c(0,1));
noLeg = ggplot2::theme(legend.position="none");
noTitle  = ggplot2::theme(plot.title=element_blank());
noXTitle = ggplot2::theme(axis.title.x=element_blank());
noTTitle = ggplot2::theme(axis.title.y=element_blank());
colour_scale=ggplot2::scale_color_hue();
fill_scale  =ggplot2::scale_fill_hue();
```

```{r LP_CalcResultsMQs}
  #--calculate model cases----
  cases = wtsUtilities::getObj(file.path(dirThs,"rda_cases.RData"));
  base = as.character(cases[1]);
  if (params$calcParams){
    lst<-list();
    for (case_ in cases){
      #--testing: case_ = cases[1];
      fn = paste0(file.path(dirThs,paste0("./LP_Results/Results_",case_,".RData")));
      if (file.exists(fn)){
        load(fn);
        if (!is.null(best$rep)){
          casep = as.character(case_);
          dfrp<-rTCSAM02::getMDFR.ManagementQuantities(best) |> 
                  dplyr::mutate(case=casep);
          lst[[casep]]<-dfrp;
          rm(casep,dfrp);
        }
        rm(best);
      }
      rm(fn);
    }#--case
    dfrMQs = dplyr::bind_rows(lst) |>        
              dplyr::select(case,type,val); #rm(lst);
    dfrMQsBase = dfrMQs |> 
                  dplyr::filter(case==base) |> 
                  dplyr::mutate(base=val) |> 
                  dplyr::select(!c(case,val));
    dfrMQds = dfrMQs |> 
               dplyr::inner_join(dfrMQsBase,
                                 by=dplyr::join_by(type)) |> 
               dplyr::mutate(diff=val-base,
                             pct=100*diff/abs(base),
                             case=as.numeric(case));
    wtsUtilities::saveObj(dfrMQds,file.path(dirThs,"rda_dfrMQsDiffs.RData"));
  }
```

```{r LPs-MQs-GetResultsMQs}
  #--plot MQ profiles
  dfrMQds = wtsUtilities::getObj(file.path(dirThs,"rda_dfrMQsDiffs.RData"));
```

```{r}
  ti = paste0(param," (",param_str,") ");
  rf = paste0("sec-LP-MQsDifs-",wtsQMD::sanitizeLabels(param));
```

## Likelihood profile results for management quantities, profiling on `r paste0(ti, " {#",rf,"}")`

```{r}
#| label: fig_LPs-MQs-
#| results: "asis"
#| fig-width: 6.0
#| fig-asp: 1
  types = c("avgRec","B100","curB","Fmsy","Fofl","MSY","OFL","prjB");
  tlbls =  c("average recruitment","unfished biomass","current biomass","directed fishing mortality that results in MSY",
             "directed fishing mortality that results in the OFL","maximum sustainable yield","overfishing limit",
             "projected biomass");
  p = ggplot(dfrMQds,aes(x=case,y=diff)) + 
        geom_hline(yintercept=0,linetype=3) +
        geom_vline(xintercept=as.numeric(cases[1]),linetype=3) +
        geom_line() + 
        facet_wrap(~type,scales="free_y") + 
        labs(x=param,y="management quantity change (value-base)") + 
        wtsPlots::getStdTheme();
  xtra=paste0("AD");
  lbl = wtsQMD::getLabel(xtra);
  cap = paste0('Absolute management quantity differences. ',
               paste0(types,": ",tlbls,collapse=", "),".");
  pth = wtsQMD::getFigFN(xtra);
  lstFigs = c(lstFigs,wtsQMD::printGGplot(p,pth=pth,lbl=lbl,cap=cap,ori="P"));

  p = ggplot(dfrMQds,aes(x=case,y=pct)) + 
        geom_hline(yintercept=0,linetype=3) +
        geom_vline(xintercept=as.numeric(cases[1]),linetype=3) +
        geom_line() + 
        facet_wrap(~type,scales="free_y") + 
        labs(x=param,y="managment quantity change as percentage: 100*(value-base)/base") + 
        wtsPlots::getStdTheme();
  xtra=paste0("PD");
  lbl = wtsQMD::getLabel(xtra);
  cap = paste0('Proportional management quantity differences.',
               paste0(types,": ",tlbls,collapse=", "),".");
  pth = wtsQMD::getFigFN(xtra);
  lstFigs = c(lstFigs,wtsQMD::printGGplot(p,pth=pth,lbl=lbl,cap=cap,ori="P"));
  rm(lbl,cap,pth)
```

<!-- references -->
```{r,eval=!knitr::opts_knit$get("child")&!isPDF,results='asis'}
  cat("# References {-}\n");
  cat("::: {#refs}\n");
  cat(":::\n\n");
```

<!-- tables, if not child doc and lstTbls is not empty -->
```{r}
#| label: tables_LPs-MQs
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printTablesSectionFromList.R",package="wtsQMD"));
```

<!-- figures, if not child doc and lstFigs is not empty -->
```{r}
#| label: figures_LPs-MQs
#| eval: !expr '!knitr::opts_knit$get("child")'
#| results: asis
  source(system.file("files/printFiguresSectionFromList.R",package="wtsQMD"));
```
